apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-stack-example1-model-config
data:
  MODEL_SERVICE_URL: "https://granite-31-8b-lab-v1-140-version-1-rhoai-workspace.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com"