apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: llama-stack-example1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: llama-stack-example1
  name: llama-stack-example1
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: llama-stack-example1
